keys:
  - &age_root age18spez0z3wvzw05nhhrka9gmjfvcvhyj7decnw9j4a9xn8m0vyexs0he23r
  - &age_mute age1gg5gdvp3kk5fd8ypuq94xyn9dtsak2exe4gdrp3k2phuffn65yzshkmeg8
  - &age_sublation age1wz326af7tgfnqpq0l6vk2p78uwp0qn9f5v5exu754rj3t8w0myvqzp4c8e
creation_rules:
   # The goal is to have my GPG key decrypt any secrets file, with
   # each file also being able to be decrypted by some other set of
   # keys. We place that GPG key last since it is password-protected
   # and should only be checked if the others fail. See the README for
   # a description of key groups:
   # https://github.com/getsops/sops?tab=readme-ov-file#215key-groups
  - path_regex: ^sublation\.yaml$
    key_groups:
      - age:
          - *age_sublation
          - *age_root
  - path_regex: ^mute\.yaml$
    key_groups:
      - age:
          - *age_mute
          - *age_root
