restic-backup-password: ENC[AES256_GCM,data:k20jPYxS3q6bmXiNqVDJLVI=,iv:fR6xVterqrVisDybvLGQXf/p04fpLWORoC+MC3zC4vo=,tag:9360FSohXE2ngdsRargg6g==,type:str]
pihole-webserver-password: ENC[AES256_GCM,data:aZ/0VN/pFJ6bmBRswT0=,iv:BNRcguvIJoVbGVbCXOR2YQPnCGdzq5K17DMqS5NkTew=,tag:AF/R0t7eRyMPPvLFOdbPbA==,type:str]
wireguard-private-key: ENC[AES256_GCM,data:oxwD1S5pXt9h9JSVPcgsHlshMKp4AlgEgfDg9C2Q5kG+38l4PR5PgXczBlY=,iv:HEt7VwV9SnFUyfDDa8cOnQXDu/1u+YxnHuihIa69Dgk=,tag:FOj+OJ1ZbpI0dXPqWLbYJg==,type:str]
vaultwarden:
    push-installation-id: ENC[AES256_GCM,data:GDoaJABdqs1vf7Suw9zZi/8lXDsHzUW+V7YLAo8dW/VF8vTZ,iv:Q/0dDCEVKN4+2JXjQp/Sk1rCW2cne+xKTe2Eq6Rb1MA=,tag:v443XYpeWhhUNOU5fkOsFQ==,type:str]
    push-installation-key: ENC[AES256_GCM,data:OTtpgHHOi7r6nnOzBW9Frw8wKvM=,iv:xcgJedstuuQi3vYrrCczu8fHJeyiPFVfrMo2cHaZwRw=,tag:E6BfSOl79dwb1XcBScrDqA==,type:str]
pocket-id-encryption-key: ENC[AES256_GCM,data:PkHXc8KW+sn0veiq+zWpTFkL6c/wwpnpkB3F8YEdxxWZlAGPf6kR9R4eQmww2x4sBuv1O9QM3BPU041M2YkLTg==,iv:otpr1uoM3OvvZSKf2Tvl8Q+ejP7AgIrQI1ibkFk4MVc=,tag:ClZhu9orak+wAH/8ZgrSHw==,type:str]
caddy:
    netlify-access-token: ENC[AES256_GCM,data:F/9cDAoglz4lIb7K3vZ4l3fwlSKBSZrNKLd4i3TQu8/DJOwnzyGsMw==,iv:aZO3F1Y1/bKGZvgVuKZfwjzsJ5CN0VW//RCwsL9Bpq0=,tag:gaukfH4KdEkJd7NRddXquw==,type:str]
    pocket-id:
        client-id: ENC[AES256_GCM,data:rCkxHKb+n22x1oH3PsGlaFB8pLIU2XqghwVnarTPfyCA/pgi,iv:t2MUPtXYOe3twbQrIG/ivCzniR9NLkDQ7XpwenVbeUY=,tag:CzE2EJC6RoD0FsswRtjQPw==,type:str]
        client-secret: ENC[AES256_GCM,data:4YcabS1RL4uY2U9fA6vZ4Rq1q4uYyo7eK7hrWGg/Smc=,iv:Sjlam6J7XfuXI4AD/eW4bWMxNG26XdFFOQlNg7zUW08=,tag:06cXbLyI5F5xb4S84/73vg==,type:str]
    crowdsec-bouncer:
        api-key: ENC[AES256_GCM,data:NE8h4DAmhCBgvLva9P0pY0FOjWsG4xQLuhfPKRFzNXW7za3GCi2IXwgicA==,iv:xlK81bUWD9gHcjQQKfJFipxsLLr/eVeegjJbzFmUOo8=,tag:EQ+jIGSNrLZPBO7xD0mIYg==,type:str]
gluetun:
    wireguard_private_key: ENC[AES256_GCM,data:wP9G5mXA0PiYEL+PZhhd182ehjcU+drTEWxReqTNeFOWd/DU+He+DtRKI3U=,iv:vOsNKeD/LQUV4QQdey3DhFN+5+szWQOEB7lrNNrkelw=,tag:U0W3iT71JpU9MVfT6LZrQg==,type:str]
    wireguard_public_key: ENC[AES256_GCM,data:3p3xaSmWLDFgLFKXKFT1oKNpVD7vPcnc03Lr4we+SFcmb1QAWc8FJaBWJQ8=,iv:SYCoAntJiJewJrUJjysp8hsFhRJdPp9r1U5BtbQI8mo=,tag:TFWK6TOR427SQbl2/1d5Gw==,type:str]
    wireguard_preshared_key: ENC[AES256_GCM,data:l47BG+asFQbs5nl7A4ChNHef/PuYQej7XoQttvABb7sawJarclSIMK4fvZs=,iv:w9uRj9mpxPGCIHGup4yMga7euXLYN5Uukkq8x003fvU=,tag:BIM8Q1T+9p/Vx5r+RB5a8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz326af7tgfnqpq0l6vk2p78uwp0qn9f5v5exu754rj3t8w0myvqzp4c8e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud05BUkViWmhtVHBuUTA0
            Mi9DZ1NkSkl6QjM4T2xoOWZHV0Fub0tkVjNJCnJQRnJ6RmNqVDQvTXRyaE1xTStC
            Q0FRVnBrN01SR01IR0lTb2h4SWFkTkUKLS0tIFBHKy9MSnA2VDlrL2xZaEZ1M0dQ
            Z213RDZpdmVlZUVkelhmQVVQVm84Ym8KrdvgKRCMPLblqYgY/CeR1eCOl9TfJIC9
            byFNrELY3rRtFMldWMAHrCOOV+Zf5tA+gEeZuhwQphYkDu/ZFor30g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18spez0z3wvzw05nhhrka9gmjfvcvhyj7decnw9j4a9xn8m0vyexs0he23r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWHRjcjRPMEhnUEsvN3lR
            Wld2TmFSYURSamVDcElRRWMwaXFERzVMakJFClFMRDJVeTFGUlBMenNjd2pLZlZn
            UU5JMFpEZmxwa0FreFBNL1RzQ004K3cKLS0tIGtQaDJxbmo1YTlmbThSV1FjWlhC
            d0tIa1FSbzJ0OFp0eHB2TVJsZnp0dkEKt4X1hYQ6fzyWN+02tFHjYDZnXicESvJI
            hmRRmSMnRusqslex4gF9PASA0YFonVUuYdxSgfDz5BWByoy1R/5WlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T22:23:06Z"
    mac: ENC[AES256_GCM,data:BPs2wBheugEnVA8wqmVFWxjJI5uY/7WxItHrj4o1N5N8IsNseOGtetVh01Val2AYXCmuG7YAX+cSaaG5quo27HfGWf8C/jSNMePOo1TbXpL0eBokFngmT/Mw5fxW/EvmkHr9SiqKXxR1LNkZ9B0ulmaSmuPrrhj841If4XTgKYE=,iv:Yi+7CaYF82OBqWbfJ11+2xuPXebyKtRnUoRaMOthpsw=,tag:8IRjTzyYgOxUjYIuFA6whw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
