restic-backup-password: ENC[AES256_GCM,data:uaGa+7iEd2nq6s+5ugcYyAE=,iv:gw6zCQ/aqCz9XVq/rYX+qXF3j4wkCvnujhfDpDgtfNQ=,tag:hNc1nzO8aIFdizs2j6uRVA==,type:str]
pihole-webserver-password: ENC[AES256_GCM,data:e1jUcXkanK1pF08NmWE=,iv:uk6haI0MZB2WGodvzOtfgXfbOO4fGOyfeG8i8UxGcec=,tag:IKx6KXvy9Gioh7jbBD+UOA==,type:str]
wireguard-private-key: ENC[AES256_GCM,data:8hUPfEn7mDgC3fkZCCgcadZIbaNmPpUSM9olU0795RM25z1MGj+4kkE2LNE=,iv:gYDRUehVYFTMdS7sKi03p1A0/BxMSk8i/m/pH7Ev6jc=,tag:9P2p/sITxp8OSC6MfDRSrQ==,type:str]
vaultwarden:
    push-installation-id: ENC[AES256_GCM,data:eR0fKRYLf4MPNsHu/1xaEoBRfAU/7lUhWd7PnycZ1tgyMiLk,iv:4GofC7GYar358Pr/A04OVzZC09IfV517u+4Rsy85Cjk=,tag:qxzo4rcc0eH2ZjLHtnRiUw==,type:str]
    push-installation-key: ENC[AES256_GCM,data:g/dJTz8T4WvUcLjZoehZkdORyB8=,iv:qvv7LFLWE4dc6lp7nxZdrLLPzbxT+FGUPzI4aFJF4CA=,tag:MA9iq+WVh5o8eXUaAKh8mg==,type:str]
pocket-id-encryption-key: ENC[AES256_GCM,data:cscO9gIx8OHwIwtZEgm9/MTw2SpoVuWjZq9B98XpLZ8JK1gEzSWi7SucRlFkLUP54XrOJ+cp6oJM0Vs81VCxMg==,iv:MWaBOHC9V5FSELGzQFg64MbOlqOTnQ6ttHg/If/s0FI=,tag:BXVuhsPPYQ2nS4gkIlO2OA==,type:str]
caddy:
    netlify-access-token: ENC[AES256_GCM,data:oq2dzyolcKCrRsVpWRtQzQ5OzYQazcfwsDmHAZ/hl3VqhAGjz2Aj4g==,iv:3znBZzmxWTOxymiwe4jeOw6sg7xpMcfK4Gt8xV7CkQ8=,tag:RxxwCuCBQPA8E1N4J+l2vQ==,type:str]
    pocket-id:
        client-id: ENC[AES256_GCM,data:OczjL2ajQdD8+ea5oaKkMq8wr8s3OVuhkLYUZ+4tnhq3BKPg,iv:ktIiXt8CBhpZe/ip2BePssxsXmCRgJLv71rlrogpA64=,tag:Hd/lUVaNp6GvPfA6miGIkw==,type:str]
        client-secret: ENC[AES256_GCM,data:rGOBtFYg9WroBeCJ0C/CLzcNcXeRBKff2ceDEZgmlXE=,iv:6k/FAy1KQKkXMrPfWec/fYhlpDBakq5x6S+eoDxAHWk=,tag:QQWkYySkaMIz14AB5GkjGg==,type:str]
    crowdsec-bouncer:
        api-key: ENC[AES256_GCM,data:BYtJ/O5wJRcCOCWZ6BUjpOaQFyDfFoXdnyil8MAYGKft2oMGXB06VZjWbQ==,iv:Wta3c7isk6ecj5rDhNJXFB2vmHWzoc7s27XpcQLPzIo=,tag:1EfvPFxaA3A4SQE9vL4T8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz326af7tgfnqpq0l6vk2p78uwp0qn9f5v5exu754rj3t8w0myvqzp4c8e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlb3J3Y1RiNWVCelRySms1
            cGNHcjRNclgvcGxTRzhIcUhldWNRSHNFU3lzCnRnc244aXZqTWRvc294VGxCVUJa
            dWJrZEhOSHNQUjNtUUZKSGxyd05ZSG8KLS0tIFJDdGJYZGVkUVpXWnpDTEtCdC9B
            WER1K21ERjVPdDRxMSt4djdrL3QwRm8K8KkVVdQgfONVP2i8SxWc0Mg1NcxhrSBX
            CARq8/lB2Z39WvkopTxCzEDXOfCtgSAqU8BadZWwJvaf834M78ge3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18spez0z3wvzw05nhhrka9gmjfvcvhyj7decnw9j4a9xn8m0vyexs0he23r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eWtGaS9Xak5kZ1E4REUx
            eWw2bjVaZFpBUGJPdk5GditNaFV4dXc5SzJ3CmRHRHQ1cnRLZURvbWpSUitoSEJ4
            QXBobVYzaXh6YUYzOVhsS2NOVWFlbXcKLS0tIFJTenVDQ1dwTU8xbE5pNEpBVjZB
            N2VtYWFVS2IzS1V3R1RmTGkzU1E1bEkKXDBHTw2losFck6xwdJa8TXX3iVmwb0E6
            LPnDjxN5cCRB82s2jXBv2WAf2UHQqGJMre/Ih2fZs9sAcHpMN4Cufw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T08:00:25Z"
    mac: ENC[AES256_GCM,data:XiSPlHygVGWQ/VXnzgZA/A+kquta9ufrN0zavmBM0mU+J2urUA+c1fMzbsd+6Gf/3rE9y5SFzIbwPviEdaow+4Vbjalbcugut/A8P6SihNycBnpDTkK0hCpeFH4c1gzTx4WXQHmQ7px1VYj1sLeH5jtXGdgEIhbLENZsMPbRcF0=,iv:n2mM+kXBUok7iA7rigV/NPaUS6UoJbHvnwogUexR6fM=,tag:VzsIkNRnAKFgpp1RfdvfDQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
