restic-backup-password: ENC[AES256_GCM,data:S4DTr2ZVibjW/LubWGXc7GI=,iv:HaSqt3m3eR1HgQVjI2RRdnpgdghOJ4eOWBvsOr54JG0=,tag:yEM1DlVTxcoTgRFf1Hh1bg==,type:str]
netlify-access-token: ENC[AES256_GCM,data:VmsS2Nyi8wNrDdE7tqjL4eInKdFTaQ6s0AAknKCKDpUmG0ILeuE9WQ==,iv:4cmEs3M2ReU4P2fYVIQulMuCJZH8YMJagmBJ0WFu9OI=,tag:8YN80Z/smaIGCwzUCy/m7Q==,type:str]
pihole-webserver-password: ENC[AES256_GCM,data:5jskd41aYlUUTd0GRsI=,iv:cXEOA1EZ7RSjUyqSaj0M8lJbp0wG45MHjRsaGMrbvAk=,tag:zQEcV+31Yw5pe8IeL4o1vQ==,type:str]
wireguard-private-key: ENC[AES256_GCM,data:yECSRYT0xAJIBA70USKqkBj9aCYx+hE01gBOrcl6phc5rgxOV70dI4hcXP0=,iv:UxVnkqF8rWhhgUXVEw94t52j+erLewrAMcOj0nEN1Eo=,tag:vSJZ3J0crWYwU5XKTjRlFA==,type:str]
vaultwarden:
    push-installation-id: ENC[AES256_GCM,data:2ZJ6M9eNnt89D1c7vcuxusIck8XB9OJ+NG76S8q6C8Tp1Gzx,iv:xB9z4t61m/pwXoI0s/0cKWznKfr50RX1kCybzph2kP4=,tag:WeDnuiiDAwY53cHQqzmpOg==,type:str]
    push-installation-key: ENC[AES256_GCM,data:JsWIpPT5tgG5jRp8xZ+lLsD6viw=,iv:jGrhLsqYgsr5JoRAa1WkUAFr3R4+hguZTpoCPTsXOqQ=,tag:CYxrawmBioybHn75paXAtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz326af7tgfnqpq0l6vk2p78uwp0qn9f5v5exu754rj3t8w0myvqzp4c8e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY2l6TU9kMG5VaW9JMlhJ
            ekdTWkgrTmZrMTlab1IvT251L1VleHpUeG53CjJlajcwWjVyNmJGUHpkWkI3VzhY
            aytVWmdNS3lEbDNkYnhpK1ZTdnRZSkEKLS0tIG00MUNhRXk2cVAyZEgvRC9NWUxv
            T3BPeDJ3R0ZMRkxQRC9uNGhQWS9GTkkKm3Canyz7yng39lBX3RovzB+RNg5YtR1H
            lV84haazkeBbuPRNZCkhYuxeEB8ppKQwdXq9sA03ZJ5rfTxpWOIo/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18spez0z3wvzw05nhhrka9gmjfvcvhyj7decnw9j4a9xn8m0vyexs0he23r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjLy83cFBhQVJaZnorK3du
            YU41U0kxRU1VUDZoaEJxM291emZ4cXVuNXcwCjZIMExja1gyblFXR3k3b2htWXhI
            Tm1mKzM5b2V6WnVuNzA2VE5EWnMvT2sKLS0tIFk4ajRFNGpZUURXcFBzTDJvdWpE
            YnFTSVBXNFZlUXpnQzMzam9nalk3VkUK2G+FGJHsHbyOSG/yBn1TnsRgInv0htSI
            XNHmSddZYJwQKbr7035QZ09wuSCHs7qng1u3KHZ4zIrl4ES0XLVLFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T13:21:58Z"
    mac: ENC[AES256_GCM,data:zh1qM4k+xsAmf0gQpPTaTLQeLyW24HjVnwbDrDM04NZ7Z0Q3V+r77/FEgrmFmNzLy20fXtBtRN3ZK2jweyMJG2IdeCyTTVvijj253M+SKfKlh7Oi2AS5skSBh1OXHBa9OIORIZ7awXKTHVHlYC1jjxSWpXcZFdeeMT7PHwvpMu8=,iv:t4kAlj9m4ilZt1c3MGX6gPRK2OWtQHRJn80OHd2ln94=,tag:TT/tH9oixaylk19Qa9Qe2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
