restic-backup-password: ENC[AES256_GCM,data:90BKmiVDr15G3TZgG+YSRwM=,iv:cY7sdzPBGMpt+yK5bJQ2nmoNsdp5pDVmWWfraGfp7cU=,tag:qsZ2kEBqVjT1fcZOulTpZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jrdxqwamp4a38ntl3938ta305rdw3j3gchkh4ycvssuw0wkzsgsskz22hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSjBqRUtiQm9iVHZXdE1I
            NitQckt0MTBKUDMwRGR4RkwwZFJBbU9BWlVFCnVCVk9oV0FYT2U1TXNacENET29u
            WEdkUGVzK21Pck1vNjA3WWtCcnVCL28KLS0tIGxrclBzOXhZZVZaR1p0R2RSYUF4
            NjZwSE9GMTFRMms4N21DM210K0I2U28KmlEGpwfocFojwL71HzNEMB0Hp0qx6TGQ
            Bc1ZGdjlu9SDbv3nZmjzYKDgesphXWRCOsBgTAczfUndhYMs4fhIBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18spez0z3wvzw05nhhrka9gmjfvcvhyj7decnw9j4a9xn8m0vyexs0he23r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkamFqWU56UWJ0RXNvWEFv
            YjJ1Y0FUeUdCMnh6MTlFMm5uTGg0bVo0WWx3Cml3dHRHZDFZQzZ1WEpjcWNTQXlv
            NDR4czNRWmVLbVZWQTBQaDJ6VzJULzQKLS0tIFJ3aUl1YkcrVHlIYlA3S3YreUZT
            ajh5ZFZ5VlFCR3I5SUdZd09PTDQrTjQKyRhB3UEdzDxJPEjDZPoSPcbbDV2JcQwW
            WQxGKk/m6FsPMns6FBTRFTXTD4FtABSS/AngHcShUmKYPEpBiQe0jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T23:34:49Z"
    mac: ENC[AES256_GCM,data:44lx2ITzRS429cz/A0gVwNPLGCRIhPNjNFSZYNqiExYtAcxaAfpnWn4SxrNJqRaVaf5Rm2sjTpFEVHzUWDhIa26qFedgUuvfsYR+/r5kCy8WOYLj0B6qk30GtE005+wQ+SVJ7vui9MXUBRrFlJq+hFaDXewRkatZ+QVLp5BPYbk=,iv:fU8iUgFb7XR4r0B3FksI2rWlQ3cduWImAMupOwDVs64=,tag:8PbishOA9hIFSrjV4YW20w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
