restic-backup-password: ENC[AES256_GCM,data:drl6mKYQaC8nIfMoGUvjlaY=,iv:IAKYAQhG4EfU1nv+GQH8Bx3mc/9ByS+O0YzCM0G2b8s=,tag:rgwXJXMUtCKsGEiUMme8pg==,type:str]
netlify-access-token: ENC[AES256_GCM,data:a4BG4e116i0YJmc4B9FBunvjcBJbFvGmcnvVYNyLdUmwT9LfEEb9EA==,iv:6w9x7nJb/NGDjfc6npDeyN8p7BkLUXh5V7jM442XeCM=,tag:mlIC8/agF3h5/9b80x8ADg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz326af7tgfnqpq0l6vk2p78uwp0qn9f5v5exu754rj3t8w0myvqzp4c8e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WUdKdG9iU2kyeEZDY2Vj
            YnFPTU1JTzBySjhFNVRUNmhtL21CUXZicHlZCjBmc2JMSXR4VklmS2JYMGdJNG9p
            dk5Ta2ZNR0JNUVlKZ1p3dThqL1NRSkEKLS0tIFJKclpQOVBVRUVKRFNLb0l3ZVMv
            SE5meUFUTUtIZTJuZjNyTWJKcVRHU0UKNpo16GDxC68TuPZ+Zjmwc9g0BZFO6fOG
            slVt5IbnsirMzoYyM9u7J6fSR73VS/qDc4/qXkACJLhOEIJEFiYz3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18spez0z3wvzw05nhhrka9gmjfvcvhyj7decnw9j4a9xn8m0vyexs0he23r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bWk0N0Zzb0NYZmxvREpL
            MFRUQThjbCtTMDFWZkhKOEEySHpyS2pKOXpRCkNvV0JTemxmOTNIbEpscWxMTnBQ
            QUNCYTJLV2RTampHa1FlM2dzR3J1WjQKLS0tIEpLVTVhM0Nuc2w3QXBaQmxkV1VY
            dmtBeXVvZVRYQ2RkcldBMERLR0tWMlkKid7vdY3iGgQB8CuDFTLGT0H5Zv3kgL8z
            glXShXaqabtDyxlEi9mSaCRMyKdyIEmm3j7Lz/WqI2cxHcqHcbkGzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T09:27:40Z"
    mac: ENC[AES256_GCM,data:T1r+mztR0c8VAUUCh5Purze+tzfCG5wchlMHmepiqgGX082biRPH69Evl+GTkWftnDHpH4+ez4dUCWEWEJjTUOotVr0ZoUYsWZkjzxEnGCa4dr4ZXUdBC04pO1jieDFOw2+NRi6pwe5KCqcv4fCt57Or1j/DTm3g6lJjtn8ojM8=,iv:+HzkXmaUkd4jhUpdnv77xHFDnETGnnLQ01xnDmPA+hs=,tag:j0ceK9om4iBkdPJpql7yOQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
