restic-backup-password: ENC[AES256_GCM,data:OgelE9tVMjx/7G/AuCmzBaQ=,iv:cY1OsLBVt6XdUoAktfuIgnuaJNaXpxbc0WUpdgSfTGc=,tag:LtG9eomWfck0XrLCOI6Wfw==,type:str]
netlify-access-token: ENC[AES256_GCM,data:mxhqgu3PBBhr+6AqLs/yve4c9wl0wDgweVxX/JbFi/hMpmMwr/EzTQ==,iv:kitN6VCLA/1RnN+yV8FjgdQGt7t/LlbOcJ5hJan1n18=,tag:ydVwncr4FGpZTU45z5E3+w==,type:str]
pihole-webserver-password: ENC[AES256_GCM,data:9GLDl4iXQC1qYdljvsM=,iv:6Eey0eN9VgXXx8t8v/ZFpMDKY85/QVXVzb3+dnzznNo=,tag:IzrZqHwCwRc5baThB4jrXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wz326af7tgfnqpq0l6vk2p78uwp0qn9f5v5exu754rj3t8w0myvqzp4c8e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycXRpMCtmYUh2a3VuUTlK
            Qm9kSkJoZS83ZE0yNlRsYWROR1lTeWVudWxRCjVlb2k2NWNiNU0rZnJjazhnM1Vn
            RldIbkJTaHZjVFVQNkprOW9aVjBJK0UKLS0tIGMvSXQyRXJNbnRidW1TeHl2NWU1
            YUQ0RDQwNnBSd25GSGhMR1pQKzdqK0UKtg26+FUrsbO4mueVqGfc3CNST4H8+lab
            KHBMjY9mhAh5okVjl4SlrE/VDyqB51I9vwHgtYkefwkkFe+kH9WQxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18spez0z3wvzw05nhhrka9gmjfvcvhyj7decnw9j4a9xn8m0vyexs0he23r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZU55d1Y4aXZvMkJmb0tT
            RU8yamVpRlBkREdQWlF1YnF5V0xPT202eFJ3CjdaVDN2MUVVWFpaTzhTcU1YQXh4
            c0FtZHpzZHJvRExZUTg4UlZSYWRBTFkKLS0tIG1IMFl1M29VMStycEp5bEVkOXdq
            YkVIR292ajdTRWtwNU4vL3dyMURpU2MKqYKC6HiDG5KIMlxY/PH3up+l9TBI3txn
            8XbzhcGCgfc1OlF5UdpHMceSBkpChwpB7pkqyhBRtvV7v4BS1kxf3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T01:20:31Z"
    mac: ENC[AES256_GCM,data:MPYj8aBlNzmcYkwNudT+bvH43WnzxBEWWrN6pqLtXg8/UdmhkMwY/3DHBqGynV4VpEWg9pvLtLj/RZ/W/FTBGWUsA5eIefJ0uKU3hf/E3ZGefqouq2V09Z5kEY+iKVIWNJYcfD3Jpt97sSxeKPlyFRZhLGAmRYZYeiRjbqBmhjI=,iv:qEZe2COPoBPDG0GlWY+w+V+A18YFrPieZklsHABVh94=,tag:O2zK3vujbNzEpOEZ56m1eA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
